apiVersion: batch/v1
kind: Job
metadata: 
  name: "demo-mlflow"
  namespace: default
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: "demo-mlflow"
        image: "docker.io/duonghm/mlflow-docker-example:latest"
        command: ["python /var/myapp/train.py --alpha 0.5 --l1-ratio 0.5"]      
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
        #env: 
        #  - name: MLFLOW_TRACKING_URI
        #    value: "http://192.168.56.1:5000"
        #  - name: MLFLOW_EXPERIMENT_ID
        #    value: "1"
      restartPolicy: Never